apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure # send traffic over HTTPS
spec:
  ingressClassName: traefik
  rules:
    - host: jannekeipert.de
      http:
        paths:
          - path: /mail-service
            pathType: Prefix
            backend:
              service:
                name: mail-service-service
                port:
                  number: 80
