kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-service-pvc
  namespace: ase-12
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
