apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  project: mail-service
  source:
    repoURL: https://github.com/Janne6565/Mail-Service-Backend
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: mailservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
